use std::{collections::BTreeSet, fmt::Write, path::PathBuf, sync::Arc};

use conduwuit::{
	Err, Result,
	config::Config,
	utils::{stream::IterStream, time},
	warn,
};
use futures::{StreamExt, TryStreamExt};

use crate::admin_command;

/// The example config embedded at compile time — generated by the
/// `config_example_generator` proc macro when `conduwuit-core` is built.
/// It contains every known config key as a commented-out entry and serves
/// as the authoritative list of what the current binary understands.
const EXAMPLE_TOML: &str = include_str!("../../../conduwuit-example.toml");

#[admin_command]
pub(super) async fn uptime(&self) -> Result {
	let elapsed = self
		.services
		.server
		.started
		.elapsed()
		.expect("standard duration");

	let result = time::pretty(elapsed);
	self.write_str(&format!("{result}.")).await
}

#[admin_command]
pub(super) async fn show_config(&self) -> Result {
	self.bail_restricted()?;

	self.write_str(&format!("{}", *self.services.server.config))
		.await
}

#[admin_command]
pub(super) async fn config_diff(&self) -> Result {
	self.bail_restricted()?;

	let cfg = &self.services.server.config;

	// Re-create the Figment from the active config paths so we can inspect
	// which keys the user *explicitly* set (vs. filled by serde defaults).
	let paths = cfg.config_paths.clone().unwrap_or_default();
	let figment = Config::load(&paths)?;

	// All known config keys extracted from the embedded example TOML.
	let known_keys = extract_known_keys_from_example();

	// For each known key, check whether the user explicitly set it.
	// figment.contains() returns true only when the key appears in one of
	// the loaded providers (TOML files / env vars), not just from defaults.
	let set_keys: Vec<&str> = known_keys
		.iter()
		.filter(|k| figment.contains(k.as_str()))
		.map(String::as_str)
		.collect();

	let missing_keys: Vec<&str> = known_keys
		.iter()
		.filter(|k| !figment.contains(k.as_str()))
		.map(String::as_str)
		.collect();

	// Keys the user set that are unknown to this binary version.
	let unknown: Vec<&str> = cfg.unknown_config_keys().collect();

	let mut out = String::new();

	writeln!(out, "## Explicitly-Set (Non-Default) Config Keys — {} set\n", set_keys.len()).ok();
	if set_keys.is_empty() {
		writeln!(out, "  (none — all values appear to be at defaults)").ok();
	} else {
		for key in &set_keys {
			writeln!(out, "  + {key}").ok();
		}
	}

	writeln!(
		out,
		"\n## Config Keys Missing From Your File — {} using defaults\n",
		missing_keys.len()
	)
	.ok();
	if missing_keys.is_empty() {
		writeln!(out, "  (none — your config covers all known options 🎉)").ok();
	} else {
		writeln!(out, "  These config options exist in this binary but are absent from your")
			.ok();
		writeln!(out, "  config file. They were added after your config was last updated.\n")
			.ok();
		for key in &missing_keys {
			writeln!(out, "  ? {key}").ok();
		}
	}

	if !unknown.is_empty() {
		writeln!(out, "\n## Unknown/Deprecated Keys In Your Config — {} found\n", unknown.len())
			.ok();
		writeln!(out, "  These keys are in your config but this binary doesn't recognise").ok();
		writeln!(out, "  them. They may be deprecated, misspelled, or from a newer version.\n")
			.ok();
		for key in &unknown {
			writeln!(out, "  ! {key}").ok();
		}
	}

	self.write_str(&out).await
}

/// Parses the embedded example TOML to build the canonical list of all
/// config keys known to this binary version. Keys are represented in
/// dot-notation mirroring how figment addresses nested fields
/// (e.g. `tls.certs`, `well_known.client`).
fn extract_known_keys_from_example() -> BTreeSet<String> {
	let mut keys = BTreeSet::new();
	let mut section_prefix = String::new();

	for line in EXAMPLE_TOML.lines() {
		let line = line.trim();

		// Handle section headers: [global], [global.tls], etc.
		if let Some(inner) = line.strip_prefix('[').and_then(|l| l.strip_suffix(']')) {
			if inner == "global" {
				section_prefix.clear();
			} else if let Some(sub) = inner.strip_prefix("global.") {
				sub.clone_into(&mut section_prefix);
			}
			continue;
		}

		// Commented-out keys look like `#key_name = ...` or `#key_name =`.
		let candidate = if let Some(rest) = line.strip_prefix('#') {
			rest
		} else {
			line
		};

		if let Some((key_part, _)) = candidate.split_once('=') {
			let key_part = key_part.trim();
			// Valid TOML bare keys: alphanumeric, underscores, dashes
			if !key_part.is_empty()
				&& key_part
					.chars()
					.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
			{
				let full_key = if section_prefix.is_empty() {
					key_part.to_owned()
				} else {
					format!("{section_prefix}.{key_part}")
				};
				keys.insert(full_key);
			}
		}
	}

	keys
}

#[admin_command]
pub(super) async fn reload_config(&self, path: Option<PathBuf>) -> Result {
	// The path argument is only what's optionally passed via the admin command,
	// so we need to merge it with the existing paths if any were given at startup.
	let mut paths = Vec::new();

	// Add previously saved paths to the argument list
	self.services
		.config
		.config_paths
		.clone()
		.unwrap_or_default()
		.iter()
		.for_each(|p| paths.push(p.to_owned()));

	// If a path is given, and it's not already in the list,
	// add it last, so that it overrides earlier files
	if let Some(p) = path {
		if !paths.contains(&p) {
			paths.push(p);
		}
	}

	self.services.config.reload(&paths)?;

	self.write_str(&format!("Successfully reconfigured from paths: {paths:?}"))
		.await
}

#[admin_command]
pub(super) async fn memory_usage(&self) -> Result {
	let services_usage = self.services.memory_usage().await?;
	let database_usage = self.services.db.db.memory_usage()?;
	let allocator_usage =
		conduwuit::alloc::memory_usage().map_or(String::new(), |s| format!("\nAllocator:\n{s}"));

	self.write_str(&format!(
		"Services:\n{services_usage}\nDatabase:\n{database_usage}{allocator_usage}",
	))
	.await
}

#[admin_command]
pub(super) async fn clear_caches(&self) -> Result {
	self.services.clear_cache().await;

	self.write_str("Done.").await
}

#[admin_command]
pub(super) async fn list_backups(&self) -> Result {
	let db = Arc::clone(&self.services.db);
	self.services
		.server
		.runtime()
		.spawn_blocking(move || db.db.backup_list().map(Iterator::collect::<Vec<_>>))
		.await??
		.into_iter()
		.stream()
		.map(Ok)
		.try_for_each(|result| writeln!(self, "{result}"))
		.await
}

#[admin_command]
pub(super) async fn backup_database(&self) -> Result {
	self.bail_restricted()?;

	let db = Arc::clone(&self.services.db);
	let result = self
		.services
		.server
		.runtime()
		.spawn_blocking(move || match db.db.backup() {
			| Ok(()) => "Done".to_owned(),
			| Err(e) => format!("Failed: {e}"),
		})
		.await?;

	let db = Arc::clone(&self.services.db);
	let count = self
		.services
		.server
		.runtime()
		.spawn_blocking(move || db.db.backup_count())
		.await??;

	self.write_str(&format!("{result}. Currently have {count} backups."))
		.await
}

#[admin_command]
pub(super) async fn admin_notice(&self, message: Vec<String>) -> Result {
	let message = message.join(" ");
	self.services.admin.send_text(&message).await;

	self.write_str("Notice was sent to #admins").await
}

#[admin_command]
pub(super) async fn reload_mods(&self) -> Result {
	self.bail_restricted()?;

	self.services.server.reload()?;

	self.write_str("Reloading server...").await
}

#[admin_command]
#[cfg(unix)]
pub(super) async fn restart(&self, force: bool) -> Result {
	use conduwuit::utils::sys::current_exe_deleted;

	if !force && current_exe_deleted() {
		return Err!(
			"The server cannot be restarted because the executable changed. If this is expected
			 use --force to override."
		);
	}

	self.services.server.restart()?;

	self.write_str("Restarting server...").await
}

#[admin_command]
pub(super) async fn shutdown(&self) -> Result {
	self.bail_restricted()?;

	warn!("shutdown command");
	self.services.server.shutdown()?;

	self.write_str("Shutting down server...").await
}

#[admin_command]
pub(super) async fn list_features(&self) -> Result {
	let mut enabled_features = conduwuit::info::introspection::ENABLED_FEATURES
		.lock()
		.expect("locked")
		.iter()
		.flat_map(|(_, f)| f.iter().map(|s| s.replace('_', "-")))
		.collect::<Vec<_>>();

	enabled_features.sort_unstable();
	enabled_features.dedup();

	let mut available_features = conduwuit::build_metadata::WORKSPACE_FEATURES
		.iter()
		.flat_map(|(_, f)| f.iter().map(|s| s.replace('_', "-")))
		.collect::<Vec<_>>();

	available_features.sort_unstable();
	available_features.dedup();

	let disabled_features: Vec<_> = available_features
		.into_iter()
		.filter(|f| !enabled_features.contains(f))
		.collect();

	let mut features = String::new();

	for feature in enabled_features {
		writeln!(features, "✓ {feature} [enabled]")?;
	}

	for feature in disabled_features {
		writeln!(features, "x {feature}")?;
	}

	self.write_str(&features).await
}

#[admin_command]
pub(super) async fn build_info(&self) -> Result {
	let mut info = String::new();

	// Version information
	writeln!(info, "# Build Information\n")?;
	writeln!(info, "**Version:** {}", env!("CARGO_PKG_VERSION"))?;
	writeln!(info, "**Package:** {}", env!("CARGO_PKG_NAME"))?;
	writeln!(info, "**Description:** {}", env!("CARGO_PKG_DESCRIPTION"))?;

	// Git information
	writeln!(info, "\n## Git Information\n")?;
	if let Some(hash) = conduwuit::build_metadata::GIT_COMMIT_HASH {
		writeln!(info, "**Commit Hash:** {hash}")?;
	}
	if let Some(hash) = conduwuit::build_metadata::GIT_COMMIT_HASH_SHORT {
		writeln!(info, "**Commit Hash (short):** {hash}")?;
	}
	if let Some(url) = conduwuit::build_metadata::GIT_REMOTE_WEB_URL {
		writeln!(info, "**Repository:** {url}")?;
	}
	if let Some(url) = conduwuit::build_metadata::GIT_REMOTE_COMMIT_URL {
		writeln!(info, "**Commit URL:** {url}")?;
	}

	// Build environment
	writeln!(info, "\n## Build Environment\n")?;
	if let Some(profile) = conduwuit::build_metadata::PROFILE {
		writeln!(info, "**Profile:** {profile}")?;
	}
	if let Some(opt) = conduwuit::build_metadata::OPT_LEVEL {
		writeln!(info, "**Optimization Level:** {opt}")?;
	}
	if let Some(debug) = conduwuit::build_metadata::DEBUG {
		writeln!(info, "**Debug:** {debug}")?;
	}
	if let Some(target) = conduwuit::build_metadata::TARGET {
		writeln!(info, "**Target:** {target}")?;
	}
	if let Some(host) = conduwuit::build_metadata::HOST {
		writeln!(info, "**Host:** {host}")?;
	}

	// Rust compiler information
	writeln!(info, "\n## Compiler Information\n")?;
	if let Some(rustc) = conduwuit::build_metadata::RUSTC_VERSION {
		writeln!(info, "**Rustc Version:** {rustc}")?;
	}

	// Target configuration
	writeln!(info, "\n## Target Configuration\n")?;
	writeln!(info, "**Architecture:** {}", std::env::consts::ARCH)?;
	writeln!(info, "**OS:** {}", std::env::consts::OS)?;
	writeln!(info, "**Family:** {}", std::env::consts::FAMILY)?;
	if let Some(endian) = conduwuit::build_metadata::CFG_ENDIAN {
		writeln!(info, "**Endianness:** {endian}")?;
	}
	if let Some(ptr_width) = conduwuit::build_metadata::CFG_POINTER_WIDTH {
		writeln!(info, "**Pointer Width:** {ptr_width} bits")?;
	}
	if let Some(env) = conduwuit::build_metadata::CFG_ENV {
		if !env.is_empty() {
			writeln!(info, "**Environment:** {env}")?;
		}
	}

	self.write_str(&info).await
}

#[admin_command]
pub(super) async fn diagnostics(&self) -> Result {
	let mut info = String::new();
	let metrics = &self.services.server.metrics;

	writeln!(info, "## Thread Pool")?;
	writeln!(info, "**Workers:** {}", metrics.num_workers())?;

	writeln!(info, "\n## Router Metrics")?;
	writeln!(
		info,
		"**Active:** {}",
		metrics
			.requests_handle_active
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;
	writeln!(
		info,
		"**Finished:** {}",
		metrics
			.requests_handle_finished
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;
	writeln!(
		info,
		"**Panics:** {}",
		metrics
			.requests_panic
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;

	writeln!(info, "\n## Aggregated Router Metrics")?;
	writeln!(
		info,
		"**Success:** {}",
		metrics
			.requests_success
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;
	writeln!(
		info,
		"**Fail:** {}",
		metrics
			.requests_fail
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;

	writeln!(info, "\n## Federation Metrics")?;
	writeln!(
		info,
		"**Transactions Processed:** {}",
		metrics
			.transactions_processed
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;
	writeln!(
		info,
		"**Transactions Last 1m:** {}",
		metrics
			.transactions_rate_1m
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;
	let total_time_us = metrics
		.transactions_time
		.load(std::sync::atomic::Ordering::Relaxed);
	let total_time_s = total_time_us / 1_000_000;
	let total_time_frac = (total_time_us % 1_000_000) / 100_000;
	writeln!(info, "**Total Processing Time:** {total_time_s}.{total_time_frac}s")?;
	writeln!(
		info,
		"**Slow Txns (>1s):** {}",
		metrics
			.transactions_slow_1s
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;
	writeln!(
		info,
		"**Slow Txns (>10s):** {}",
		metrics
			.transactions_slow_10s
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;

	writeln!(info, "\n## Aggregated DNS Metrics")?;
	writeln!(
		info,
		"**Success:** {}",
		metrics
			.dns_requests_success
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;
	writeln!(
		info,
		"**Fail:** {}",
		metrics
			.dns_requests_fail
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;

	writeln!(info, "\n## Background Tasks")?;
	writeln!(
		info,
		"**Presence Updates:** {}",
		metrics
			.presence_pending_updates
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;
	writeln!(
		info,
		"**Active Backfill Rooms:** {}",
		metrics
			.federation_active_rooms
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;
	writeln!(
		info,
		"**Outbound Sending Queue:** {}",
		metrics
			.sending_queue_total
			.load(std::sync::atomic::Ordering::Relaxed)
	)?;

	self.write_str(&info).await
}
