# fast compile time, decent runtime, no debug asserts, but still debuggable
[profile.release-quick]
debug            = "full"
debug-assertions = false
incremental      = true
inherits         = "release"
lto              = "off"
opt-level        = 1
strip            = "none"

# Dev/testing build with fast compile time, decent runtime performance.
# Here, "quick" refers to compile time, not runtime speed.
# NOTE: for smaller binaries on disk, put: strip = "symbols"
[profile.dev-quick]
codegen-units = 256
debug         = "full"
incremental   = true
inherits      = "dev"
lto           = "off"
opt-level     = 0
strip         = "none"
