# fast compile time, decent runtime, no debug asserts, but still debuggable
[profile.release-quick]
inherits = "release"
opt-level = 1
debug = "full"
strip = "none"
debug-assertions = false
incremental = true
lto = "off"

# Dev/testing build with fast compile time, decent runtime performance.
# Here, "quick" refers to compile time, not runtime speed.
# NOTE: for smaller binaries on disk, put: strip = "symbols"
[profile.dev-quick]
inherits = "dev"
opt-level = 0
debug = "full"
strip = "none"
lto = "off"
codegen-units = 16
incremental = true

[workspace.package]
# I, Shane Jaroch, hereby add AGPL-3.0 to my repository (fork)'s license,
# on the 23rd of March, 2026, this change intended to be temporary.
license = "Apache-2.0 AND AGPL-3.0"
