# shellcheck shell=bash

# List available commands
_help:
    @just --list

COMPLEMENT_IMAGE := env_var_or_default("COMPLEMENT_IMAGE", "continuwuity:complement")
COMPLEMENT_BASE_IMAGE := env_var_or_default("COMPLEMENT_BASE_IMAGE", "ubuntu:latest")
PROFILE := env_var_or_default("PROFILE", "release")

ci-complement-docker: # Build docker image from existing binary
    #!/usr/bin/env bash
    set -euo pipefail

    echo "Copying dynamically linked libraries to target/${PROFILE}/lib/..."
    mkdir -p target/${PROFILE}/lib && rm -f target/${PROFILE}/lib/*

    LD_LIBRARY_PATH="${ROCKSDB_LIB_DIR:-}:$(echo ${LD_LIBRARY_PATH:-})" \
        ldd target/latest/conduwuit | awk '/=> \// {print $3}' \
        | grep -vE 'libc\.so|libm\.so|libgcc_s\.so|libstdc\+\+\.so|ld-linux|libdl\.so|libpthread\.so|librt\.so' \
        | xargs -I {} cp "{}" target/${PROFILE}/lib/ || true

    rm -rf target/latest/lib
    ln -sfn ../${PROFILE}/lib target/latest/lib

    echo "Building Complement Docker image using base image: ${COMPLEMENT_BASE_IMAGE}..."
    DOCKER_BUILDKIT=1 docker buildx build \
            --build-arg BASE_IMAGE=${COMPLEMENT_BASE_IMAGE} \
            --build-arg BINARY_PATH=target/latest/conduwuit \
            --build-arg LIB_PATH=target/${PROFILE}/lib \
            --build-arg UID="$(id -u)" \
            --build-arg GID="$(id -g)" \
            -t ${COMPLEMENT_IMAGE} \
            -f ./docker/complement.Dockerfile \
            --load .

# Aggregates test results generated by complement
ci-complement-stats:
    #!/usr/bin/env bash
    set -euo pipefail

    RESULTS="tests/test_results/complement/test_results.jsonl"
    if [ ! -f "$RESULTS" ]; then
        echo "ERROR: $RESULTS does not exist"
        exit 1
    fi

    echo "Parsing Complement test results..."
    PASS=$(jq -s '[.[] | select(.Action == "pass")] | length' "$RESULTS")
    FAIL=$(jq -s '[.[] | select(.Action == "fail")] | length' "$RESULTS")
    SKIP=$(jq -s '[.[] | select(.Action == "skip")] | length' "$RESULTS")
    TOTAL=$((PASS + FAIL + SKIP))

    echo ""
    if [ "$FAIL" -gt 0 ] && [ "${VERBOSE:-0}" = "1" ]; then
        echo "Failed Tests:"
        jq -r 'select(.Action == "fail") | .Test' "$RESULTS" | sort -u
        echo ""
    fi

    echo "=== Complement Test Stats ==="
    echo "✓ Passed:  $PASS"
    echo "✗ Failed:  $FAIL"
    echo "⚠ Skipped: $SKIP"
    echo "Overall:   $TOTAL tests"

    echo ""
    echo "Last modified by:"
    git log -5 --format="%an (%ad) %H" origin/main -- tests/test_results/complement/test_results.jsonl
