# Continuwuity

services:
    homeserver:
        image: forgejo.ellis.link/continuwuation/continuwuity:latest
        restart: unless-stopped
        command: /sbin/conduwuit
        ports:
            - 127.0.0.1:8008:8008
        dns:
            - 10.10.10.20
        depends_on:
            - unbound
        networks:
            - continuwuity_net
        volumes:
            - db:/var/lib/continuwuity
            #- ./continuwuity.toml:/etc/continuwuity.toml
        environment:
            CONTINUWUITY_SERVER_NAME: example.com # EDIT THIS
            CONTINUWUITY_DATABASE_PATH: /var/lib/continuwuity
            CONTINUWUITY_ADDRESS: 0.0.0.0
            CONTINUWUITY_PORT: 8008
            #CONTINUWUITY_CONFIG: '/etc/continuwuity.toml' # Uncomment if you mapped config toml above

            ## (Optional) Serve .well-known files to tell others to reach Continuwuity on port :443
            ## If you do this, remove all routes to port :8448 on your reverse proxy
            # CONTINUWUITY_WELL_KNOWN: |
            #     {
            #     client=https://example.com,
            #     server=example.com:443
            #     }

    unbound:
        image: madnuttah/unbound:latest
        restart: unless-stopped
        networks:
            continuwuity_net:
                ipv4_address: 10.10.10.20

networks:
    continuwuity_net:
        ipam:
            config:
                - subnet: 10.10.10.0/24

volumes:
    db:
